"""
Django settings for Alpaca-chan project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
#! TODO https://docs.djangoproject.com/en/4.0/ref/settings/#core-settings-topical-index

import sys
import secrets
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT_DIR = BASE_DIR.parent
PROJECT_APPLICATIONS = PROJECT_ROOT_DIR / 'applications'

for app in PROJECT_APPLICATIONS.iterdir():
    if str(app) not in sys.path:
        sys.path.append(str(app))


# <development settings>
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# https://docs.djangoproject.com/en/4.0/ref/settings/#secret-key
key = PROJECT_ROOT_DIR / '.SECRET_KEY'
if key.exists():
    with open(key, 'r') as f: SECRET_KEY = f.read().strip()
else:
    print("!WARNING -- Can't find SECRET_KEY, a random token will be generated.")
    SECRET_KEY = secrets.token_urlsafe(49)
del key

# As a security measure, Django will exclude from debug pages any setting
# whose name partial includes any of the following:
# 'API', 'KEY', 'PASS', 'SECRET', 'SIGNATURE', 'TOKEN'
DEBUG = True

# If DEBUG is False, you also need to properly set the ALLOWED_HOSTS setting
ALLOWED_HOSTS = ['example.com', 'test.com', 'localhost', '127.0.0.1', '[::1]']

# </development settings>


# <application definition>
# https://docs.djangoproject.com/en/4.0/ref/applications/

ROOT_URLCONF = 'alpaca.urls'

WSGI_APPLICATION = 'alpaca.wsgi.application'

INSTALLED_APPS = [
    'polls.apps.PollsConfig',
    'encyclopedia.apps.EncyclopediaConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# TODO
# https://docs.djangoproject.com/en/4.0/ref/settings/#static-files
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = 'static/'

MEDIA_ROOT = PROJECT_ROOT_DIR / 'file-storage'

# </application definition>


# <database>
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'django-main.sqlite3',
        'TIME_ZONE': 'Europe/Moscow',
    },
    'polls_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_APPLICATIONS / 'django-polls' / 'polls.sqlite3',
        'TIME_ZONE': 'Europe/Moscow',
    },
    'encyclopedia_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': PROJECT_APPLICATIONS / 'django-cs50-wiki' / 'encyclopedia.sqlite3',
        'TIME_ZONE': 'Europe/Moscow',
    },
}
# TODO disable AUTOCOMMIT for other db-es
#     The test database https://docs.djangoproject.com/en/4.0/topics/testing/overview/#the-test-database
#     https://docs.djangoproject.com/en/4.0/ref/settings/#test

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DATABASE_ROUTERS
# https://docs.djangoproject.com/en/4.0/topics/db/multi-db/#topics-db-multi-db-routing
# https://stackoverflow.com/questions/13756356/different-databases-for-different-apps-in-django
DATABASE_ROUTERS = [
    'polls.db_router.PollsRouter',
    'encyclopedia.db_router.WikiRouter',
]
# </database>


# <password>
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# </password>


# <internationalization>
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_COOKIE_SECURE = True

LANGUAGE_CODE = 'en-us'
USE_L10N = False

DEFAULT_CHARSET = 'utf-8'

TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

DATE_FORMAT = 'Y.n.j'
SHORT_DATE_FORMAT = 'Y.n.j P'
TIME_FORMAT = 'G:i:s'
DATETIME_FORMAT = 'Y.n.j G:i:s'

# </internationalization>


#? File upload
# https://docs.djangoproject.com/en/4.0/topics/files/


# E-mail TODO
# https://docs.djangoproject.com/en/4.0/topics/email/


# Logging TODO
# https://docs.djangoproject.com/en/4.0/ref/settings/#logging
# https://docs.djangoproject.com/en/4.0/topics/logging/#configuring-logging
# https://docs.djangoproject.com/en/4.0/ref/settings/#message-level


# Testing TODO
# https://docs.djangoproject.com/en/4.0/ref/settings/#test-runner
# https://docs.djangoproject.com/en/4.0/topics/testing/advanced/#other-testing-frameworks


# Sessions TODO
# https://docs.djangoproject.com/en/4.0/ref/settings/#sessions


# <misc>

APPEND_SLASH = False

CSRF_COOKIE_SECURE = True

# </misc>
