# Generated by Django 4.0.6 on 2022-07-13 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=150, verbose_name='name')),
                ('entry_text', models.TextField(verbose_name='text')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date published')),
                ('upd_date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='last update')),
            ],
        ),
    ]
