# Generated by Django 4.0.6 on 2022-07-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_alter_entry_options_alter_entry_entry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL Shortcut'),
        ),
    ]
