# Generated by Django 4.1 on 2022-08-05 13:18

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=30, verbose_name='category label')),
                ('money', models.FloatField(default=0, verbose_name='money on account')),
            ],
            options={
                'verbose_name': 'auctioneer',
                'verbose_name_plural': 'auctioneers',
                'db_table': 'auctions_profile',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
