# Generated by Django 4.1 on 2022-08-04 14:34

import auctions.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_value', models.FloatField(default=1)),
                ('bid_date', models.DateTimeField(db_index=True, default=django.utils.timezone.localtime)),
            ],
            options={
                'verbose_name': 'placed bid',
                'verbose_name_plural': 'placed bets',
                'db_table': 'auctions_bids',
                'ordering': ['-bid_date'],
                'get_latest_by': ['-bid_date'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=300, verbose_name='listing title')),
                ('description', models.TextField(verbose_name='listing description')),
                ('image', models.ImageField(max_length=500, upload_to=auctions.models.user_media_path, verbose_name='visual presentation')),
                ('starting_price', models.FloatField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='created')),
                ('date_published', models.DateTimeField(default=None, null=True, verbose_name='published')),
                ('is_active', models.BooleanField(default=False, verbose_name='is listing published?')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'db_table': 'auctions_listing',
                'ordering': ['-date_published', '-date_created'],
                'get_latest_by': ['-date_published', '-date_created'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=100, verbose_name='category label')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'auctions_category',
                'ordering': ['label'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('slug', models.SlugField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
                ('money', models.FloatField(default=0, verbose_name='money on account')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'auctions_profile',
                'ordering': ['slug'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionsUser',
            fields=[
            ],
            options={
                'verbose_name': 'auctioneer',
                'verbose_name_plural': 'auctioneers',
                'db_table': 'auctions_user',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.userprofile')),
            ],
            options={
                'verbose_name': 'watchlist',
                'verbose_name_plural': 'watchlists',
                'db_table': 'auctions_watchlists',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to='auctions.auctionsuser', verbose_name='profile′s owner'),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.listingcategory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='in_watchlist',
            field=models.ManyToManyField(through='auctions.Watchlist', to='auctions.userprofile'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings_owned', related_query_name='listing', to='auctions.userprofile'),
        ),
        migrations.AddField(
            model_name='listing',
            name='potential_buyers',
            field=models.ManyToManyField(related_name='placed_bets', related_query_name='bid', through='auctions.Bid', to='auctions.userprofile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='comment text')),
                ('pub_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='comment published')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.userprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing', verbose_name='commentary on')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'auctions_comment',
                'ordering': ['-pub_date'],
                'get_latest_by': ['-pub_date'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='auctioneer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.userprofile'),
        ),
        migrations.AddField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['slug'], name='auctions_li_slug_ae2424_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['date_published', 'date_created'], name='auctions_li_date_pu_2a1459_idx'),
        ),
    ]
