# Generated by Django 4.1 on 2022-08-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_listing_watchlist_listing_in_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': ['-bid_value'], 'ordering': ['-bid_date'], 'verbose_name': 'placed bid', 'verbose_name_plural': 'placed bets'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='in_watchlist',
            field=models.ManyToManyField(related_name='items_watched', through='auctions.Watchlist', to='auctions.profile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lots_owned', to='auctions.profile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potential_buyers',
            field=models.ManyToManyField(related_name='placed_bets', through='auctions.Bid', to='auctions.profile'),
        ),
    ]
