# Generated by Django 4.1 on 2022-08-08 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_options_alter_listing_in_watchlist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': ['bid_value'], 'ordering': ['-bid_date'], 'verbose_name': 'placed bid', 'verbose_name_plural': 'placed bets'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date_published', '-date_created'], 'verbose_name': 'listing', 'verbose_name_plural': 'listings'},
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.FloatField(db_index=True, verbose_name='value'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='auctions.profile')),
            ],
            options={
                'verbose_name': 'auctioneer log',
                'verbose_name_plural': 'auctioneer logs',
                'db_table': 'auctions_logs',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
