# Generated by Django 4.1 on 2022-08-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date'], 'verbose_name': 'auctioneer log', 'verbose_name_plural': 'auctioneer logs'},
        ),
    ]
