# Generated by Django 4.1 on 2022-08-21 07:36

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_date_published_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date_published', '-date_created', 'slug'], 'verbose_name': 'listing', 'verbose_name_plural': 'listings'},
        ),
        migrations.AddField(
            model_name='profile',
            name='user_model_pk',
            field=models.IntegerField(blank=True, null=True, verbose_name='the users pk on the User model'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(max_length=300, upload_to=auctions.models.user_media_path, verbose_name='visual presentation'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
