# Generated by Django 4.1 on 2022-08-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
