# Generated by Django 4.1 on 2022-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
