# Generated by Django 4.1 on 2022-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['profile'], 'verbose_name': 'watchlist', 'verbose_name_plural': 'watchlists'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_model_pk',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='the users pk on the User model'),
        ),
    ]
