# Generated by Django 4.1 on 2022-08-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_watchlist_options_alter_profile_user_model_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['listing'], 'verbose_name': 'watchlist', 'verbose_name_plural': 'watchlists'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_model_pk',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='user.pk'),
        ),
    ]
