# Generated by Django 4.1 on 2022-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_watchlist_options_alter_profile_user_model_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'get_latest_by': ['bid_value'], 'ordering': ['-bid_date'], 'verbose_name': 'placed bid', 'verbose_name_plural': 'placed bids'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='potential_buyers',
            field=models.ManyToManyField(related_name='placed_bids', through='auctions.Bid', to='auctions.profile'),
        ),
    ]
