# Generated by Django 4.1 on 2022-08-05 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL Shortcut (slug)')),
                ('entry_name', models.CharField(max_length=150, verbose_name='Article Name')),
                ('entry_text', models.TextField(verbose_name='Article Text')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Date Published')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Wiki Entry',
                'verbose_name_plural': 'Wiki Entries',
                'ordering': ['entry_name'],
            },
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['slug'], name='encyclopedi_slug_bb809a_idx'),
        ),
    ]
