# Generated by Django 4.0.6 on 2022-07-17 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['entry_name'], 'verbose_name': 'Wiki Entry', 'verbose_name_plural': 'Wiki Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_name',
            field=models.CharField(max_length=150, verbose_name='Article Name'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(verbose_name='Article Text'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update'),
        ),
    ]
