# Generated by Django 4.1 on 2022-08-22 12:19

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['entry_name'], 'verbose_name': 'wiki entry', 'verbose_name_plural': 'wiki entries'},
        ),
        migrations.AlterModelManagers(
            name='entry',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_name',
            field=models.CharField(max_length=150, verbose_name='article name'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(verbose_name='article text'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='upd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
    ]
